baseURL = 'https://noomatic.co'
languageCode = 'en-us'
title = 'Noomatic'
rssLimit = 10

[menu]
[[menu.main]]
name = 'Home'
URL = '/'
weight = 1
[[menu.main]]
name = 'Services'
URL = '/services/'
weight = 2